# Font
font_family JetBrainsMono Nerd Font
font_size 11


# Window
window_padding_width 8
background_opacity 0.50
confirm_os_window_close 0
background_blur 100

# Cursor
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# Scrollback
scrollback_lines 10000

# Bell
enable_audio_bell no

# Tabs
tab_bar_style powerline
tab_powerline_style round

# Colors

color0  #2B1645
color1  #FF3D81
color2  #D946EF
color3  #FF70D9
color4  #00B8FF
color5  #FF4DFF
color6  #00FFF0
color7  #FFFFFF

color8  #9D4EDD
color9  #FF5C9A
color10 #E879F9
color11 #FF9AE6
color12 #33C7FF
color13 #FF66FF
color14 #33FFF2
color15 #FFFFFF

foreground #F8F4FF
background #12091F

foreground #CDD6F4
background #1E1E2E

# Selection
selection_foreground #1E1E2E
selection_background #89B4FA


