# Font
font_family JetBrainsMono Nerd Font
font_size 11


# Window
window_padding_width 8
background_opacity 0.50
confirm_os_window_close 0
background_blur 100

# Cursor
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# Scrollback
scrollback_lines 10000

# Bell
enable_audio_bell no

# Tabs
tab_bar_style powerline
tab_powerline_style round

# Colors

color0  #1A1520
color1  #D78EE2
color2  #825EBC
color3  #7069CC
color4  #6258B5
color5  #A56CCF
color6  #C47BDD
color7  #E8D5F0

color8  #3A2942
color9  #E3A0EC
color10 #9670CC
color11 #8580E0
color12 #776DD1
color13 #B97ADE
color14 #D694E8
color15 #F5E8F8

foreground #CDD6F4
background #1E1E2E

# Selection
selection_foreground #1E1E2E
selection_background #89B4FA


